In [2]:
import pandas as pd
import numpy as np

In [3]:
sample_data= {'Date': ['2025-03-22','2025-03-23','2025-03-24']}
sample_df=pd.DataFrame(data=sample_data)

In [4]:
sample_df

         Date
0  2025-03-22
1  2025-03-23
2  2025-03-24

In [ ]:
sample_df.info() #object - considering as categorical variable

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

We have date columns but Date is not consider as Date instead it is considering as object-categorical data

In [10]:
sample_df['converted_datetime']=pd.to_datetime(sample_df['Date'])

In [11]:
sample_df.info() #datetime64[ns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Date                3 non-null      object
 1   converted_datetime  3 non-null      datetime64[ns]
dtypes: datetime64[ns](1), object(1)
memory usage: 180.0+ bytes

Here if we have DateTime object variable we can easily separate variable based on date/time/year

In [12]:
sample_df

         Date converted_datetime
0  2025-03-22         2025-03-22
1  2025-03-23         2025-03-23
2  2025-03-24         2025-03-24

Formatting DATe

In [39]:
sample_data2= {'Date': ['22-03-2025','23-03-2025','24-03-2025']}
sample_df2=pd.DataFrame(data=sample_data2)

In [40]:
sample_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 1 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    3 non-null      object
dtypes: object(1)
memory usage: 156.0+ bytes

In [41]:
sample_df2

         Date
0  22-03-2025
1  23-03-2025
2  24-03-2025

In [43]:
sample_df2['converted_datetime']=pd.to_datetime(sample_df2['Date'], format='%d-%m-%Y')

In [44]:
sample_df2

         Date converted_datetime
0  22-03-2025         2025-03-22
1  23-03-2025         2025-03-23
2  24-03-2025         2025-03-24

Extracting specific data to create particular columns

In [45]:
sample_df2['Month']= sample_df2['converted_datetime'].dt.month

In [48]:
sample_df2['Day']=sample_df2['converted_datetime'].dt.day

In [50]:
sample_df2['Year']=sample_df2['converted_datetime'].dt.year

In [51]:
sample_df2

         Date converted_datetime  Month  Day  Year
0  22-03-2025         2025-03-22      3   22  2025
1  23-03-2025         2025-03-23      3   23  2025
2  24-03-2025         2025-03-24      3   24  2025

### Using DateTime library to convert DateTime