In [220]:
import pandas as pd
import numpy as np

## Basic Level Exploration

### Load titanic.csv and print df.info() and df.isna().sum(). What are the missing counts?

In [221]:
df= pd.read_csv('../../Data_Files/Titanic.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [222]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [223]:
df.sample(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
508,509,0,3,"Olsen, Mr. Henry Margido",male,28.0,0,0,C 4001,22.5250,NaN,S
392,393,0,3,"Gustafsson, Mr. Johan Birger",male,28.0,2,0,3101277,7.9250,NaN,S
555,556,0,1,"Wright, Mr. George",male,62.0,0,0,113807,26.5500,NaN,S
456,457,0,1,"Millet, Mr. Francis Davis",male,65.0,0,0,13509,26.5500,E38,S
340,341,1,2,"Navratil, Master. Edmond Roger",male,2.0,1,1,230080,26.0000,F2,S
172,173,1,3,"Johnson, Miss. Eleanor Ileen",female,1.0,1,1,347742,11.1333,NaN,S
337,338,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C
435,436,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S
343,344,0,2,"Sedgwick, Mr. Charles Frederick Waddington",male,25.0,0,0,244361,13.0000,NaN,S
479,480,1,3,"Hirvonen, Miss. Hildur E",female,2.0,0,1,3101298,12.2875,NaN,S

In [224]:
df.describe(include='all')

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
count,891.000000,891.000000,891.000000,891,891,714.000000,891.000000,891.000000,891,891.000000,204,889
unique,NaN,NaN,NaN,891,2,NaN,NaN,NaN,681,NaN,147,3
top,NaN,NaN,NaN,"Braund, Mr. Owen Harris",male,NaN,NaN,NaN,347082,NaN,G6,S
freq,NaN,NaN,NaN,1,577,NaN,NaN,NaN,7,NaN,4,644
mean,446.000000,0.383838,2.308642,NaN,NaN,29.699118,0.523008,0.381594,NaN,32.204208,NaN,NaN
std,257.353842,0.486592,0.836071,NaN,NaN,14.526497,1.102743,0.806057,NaN,49.693429,NaN,NaN
min,1.000000,0.000000,1.000000,NaN,NaN,0.420000,0.000000,0.000000,NaN,0.000000,NaN,NaN
25%,223.500000,0.000000,2.000000,NaN,NaN,20.125000,0.000000,0.000000,NaN,7.910400,NaN,NaN
50%,446.000000,0.000000,3.000000,NaN,NaN,28.000000,0.000000,0.000000,NaN,14.454200,NaN,NaN
75%,668.500000,1.000000,3.000000,NaN,NaN,38.000000,1.000000,0.000000,NaN,31.000000,NaN,NaN
max,891.000000,1.000000,3.000000,NaN,NaN,80.000000,8.000000,6.000000,NaN,512.329200,NaN,NaN

### Show df.dtypes. Convert Sex and Embarked to category. How much memory saved?

In [225]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [226]:
df.memory_usage(deep=True).sum()

np.int64(292464)

In [227]:
#astype('category')
df[['Cabin','Embarked']]=df[['Cabin','Embarked']].astype('category')

In [228]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    category
 11  Embarked     889 non-null    category
dtypes: category(2), float64(2), int64(5), object(3)
memory usage: 77.7+ KB

In [229]:
df.memory_usage(deep=True).sum()

# Before = np.int64(292464)
# after : np.int64(230037)

np.int64(230037)

### Use .loc to select rows where Pclass == 1 and Sex == 'female' and show first 5 names.

In [303]:
df.loc[(df['Pclass']==1) & (df['Sex']=='female'), "Name"].head(5)

1     Cumings, Mrs. John Bradley (Florence Briggs Th...
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)
11                             Bonnell, Miss. Elizabeth
31       Spencer, Mrs. William Augustus (Marie Eugenie)
52             Harper, Mrs. Henry Sleeper (Myna Haxtun)
Name: Name, dtype: object

### Extract Title from Name using str.extract.

In [306]:
df['Title']= df['Name'].str.extract(r',\s*([^\.])+\.')
df['Title'].value_counts()

Title
r    568
s    309
v      6
e      3
l      2
n      1
y      1
t      1
Name: count, dtype: int64

In [307]:
df['Name'].str.contains('Mrs.',regex=True, na=False)

0      False
1       True
2      False
3       True
4      False
       ...
886    False
887    False
888    False
889    False
890    False
Name: Name, Length: 891, dtype: bool

### Demonstrate query() with a variable: select rows where Age > threshold and Pclass==p.

In [309]:

df.query("Age > 35 and Pclass==1").head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Fare_bin,Survived_bool,Survived_label,Surname,FirstName,Sex_code,Embarked_code,Deck_code,Cabin_list,Title
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,...,3,True,servived,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,0,2,[C85],s
6,7,0,1,"McCarthy, Mr. Timothy J",male,54,0,0,17463,51.8625,...,3,False,died,McCarthy,Mr. Timothy J,1,2,4,[E46],r
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,...,2,True,servived,Bonnell,Miss. Elizabeth,0,2,2,[C103],s
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40,0,0,PC 17601,27.7208,...,2,False,died,Uruchurtu,Don. Manuel E,1,0,8,[],n
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42,1,0,113789,52.0000,...,3,False,died,Holverson,Mr. Alexander Oskar,1,2,8,[],r

### Detect mixed types in Ticket column: show types and counts.

In [310]:
df['Ticket'].map(lambda x : type(x)).value_counts()

Ticket
<class 'str'>    891
Name: count, dtype: int64

### Use select_dtypes to create a DataFrame df_num containing only numeric types for feeding to a scaler.

In [313]:
df_num= df.select_dtypes(include=['number']).copy()
df_num.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PassengerId    891 non-null    int64
 1   Survived       891 non-null    int64
 2   Pclass         891 non-null    int64
 3   Age            891 non-null    int64
 4   SibSp          891 non-null    Int8
 5   Parch          891 non-null    Int8
 6   Fare           891 non-null    float64
 7   FamilySize     891 non-null    Int8
 8   Fare_bin       891 non-null    int64
 9   Sex_code       891 non-null    int8
 10  Embarked_code  891 non-null    int8
 11  Deck_code      891 non-null    int8
dtypes: Int8(3), float64(1), int64(5), int8(3)
memory usage: 49.7 KB

### You receive a CSV where Age is sometimes "." or "n/a". Show how to parse such tokens as NaN using na_values and confirm result.

In [317]:
df_new= pd.read_csv('../../Data_Files/Titanic.csv', na_values=['','n/a','-','--',' ','NA','NaN'])
df_new.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

### You must select rows where:

Age > 40

Fare is between 20 and 100

Sex is female

Survived is true

But you must use .loc, NOT chained indexing.

In [319]:
df.loc[(df['Age']> 40) & (df['Fare'].between(20,100))& (df['Sex']=='female')&(df['Survived'])].head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Fare_bin,Survived_bool,Survived_label,Surname,FirstName,Sex_code,Embarked_code,Deck_code,Cabin_list,Title
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58,0,0,113783,26.5500,...,2,True,servived,Bonnell,Miss. Elizabeth,0,2,2,[C103],s
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49,1,0,PC 17572,76.7292,...,3,True,servived,Harper,Mrs. Henry Sleeper (Myna Haxtun),0,0,3,[D33],s
194,195,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44,0,0,PC 17610,27.7208,...,2,True,servived,Brown,Mrs. James Joseph (Margaret Tobin),0,0,1,[B4],s
259,260,1,2,"Parrish, Mrs. (Lutie Davis)",female,50,0,1,230433,26.0000,...,2,True,servived,Parrish,Mrs. (Lutie Davis),0,2,8,[],s
275,276,1,1,"Andrews, Miss. Kornelia Theodosia",female,63,1,0,13502,77.9583,...,3,True,servived,Andrews,Miss. Kornelia Theodosia,0,2,3,[D7],s

In [327]:
df[['Fare','SibSp','Parch']].info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Fare    891 non-null    float64
 1   SibSp   891 non-null    Int8
 2   Parch   891 non-null    Int8
dtypes: Int8(2), float64(1)
memory usage: 10.6 KB

### Convert Fare to numeric safely (coerce errors) and print min/max. Why use to_numeric(..., errors='coerce')?

In [230]:
df['Fare']= pd.to_numeric(df['Fare'], errors='coerce')

In [231]:
df['Fare'].min()

np.float64(0.0)

In [232]:
df['Fare'].max()

np.float64(512.3292)

### Is PassengerId unique? Verify and return duplicates if any.

In [233]:
assert df['PassengerId'].is_unique

In [234]:
df[df['PassengerId'].duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked]
Index: []

### Convert SibSp and Parch to integer Int8 (nullable integer). Explain difference to int8.

In [235]:
df[['SibSp','Parch']]= df[['SibSp','Parch']].astype('Int8')

In [236]:
df.dtypes
# Int8 support NA while int8 does not

PassengerId       int64
Survived          int64
Pclass            int64
Name             object
Sex              object
Age             float64
SibSp              Int8
Parch              Int8
Ticket           object
Fare            float64
Cabin          category
Embarked       category
dtype: object

###  Print df['Embarked'].value_counts(dropna=False). How many missing? How would you fill them?

In [237]:
df['Embarked'].value_counts(dropna=False)

Embarked
S      644
C      168
Q       77
NaN      2
Name: count, dtype: int64

In [238]:
values= df['Embarked'].mode()
df['Embarked']=df['Embarked'].fillna(values)

In [239]:
df['Embarked'].value_counts(dropna=False) 
df['Embarked'].dtype

CategoricalDtype(categories=['C', 'Q', 'S'], ordered=False, categories_dtype=object)

### Create FamilySize = SibSp + Parch + 1. Show its distribution. What dtype should it be?

In [240]:
df[['SibSp','Parch']].dtypes

SibSp    Int8
Parch    Int8
dtype: object

In [241]:
# creating new column FamilySize = SibSp + Parch +1
df['FamilySize']= df['SibSp']+df['Parch']+1 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    Int8
 7   Parch        891 non-null    Int8
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    category
 11  Embarked     889 non-null    category
 12  FamilySize   891 non-null    Int8
dtypes: Int8(3), category(2), float64(2), int64(3), object(3)
memory usage: 69.0+ KB

### Extract Title from Name using regex and show the top titles and counts.

In [242]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

### Make IsAlone boolean where FamilySize == 1 (use nullable bool).

In [243]:
df['IsAlone']= (df['FamilySize']==1).astype('boolean')

In [244]:
df['IsAlone'].value_counts()

IsAlone
True     537
False    354
Name: count, dtype: Int64

###  How many unique ticket prefixes exist? Extract prefix from Ticket (non-numeric part) and show top 10 counts.

In [245]:
df['Ticket'].head(10)

0           A/5 21171
1            PC 17599
2    STON/O2. 3101282
3              113803
4              373450
5              330877
6               17463
7              349909
8              347742
9              237736
Name: Ticket, dtype: object

In [246]:
# creating prefix column
df['TicketPrefix']= df['Ticket'].str.replace(r'\d+',' ').str.strip().replace('','NO_PREFIX')

In [247]:
df['TicketPrefix'].value_counts()

TicketPrefix
347082              7
1601                7
CA. 2343            7
3101295             6
CA 2144             6
                   ..
PC 17590            1
17463               1
330877              1
373450              1
STON/O2. 3101282    1
Name: count, Length: 681, dtype: int64

## Intermediate Level Exploration

### Convert Age to Int64 after filling missing with median per Title

In [248]:
df['Age'].dtype

dtype('float64')

In [249]:
## fll missing value - 
df['Age']= df['Age'].fillna(df['Age'].median())

In [250]:
## first we need to fill all missing values if directly try to convert it shows error

df['Age']=df['Age'].astype('int64')

In [251]:
df['Age'].head()

0    22
1    38
2    26
3    35
4    35
Name: Age, dtype: int64

### Create Deck from Cabin first letter; set missing to 'Unknown' as category.

In [252]:
df['Cabin'].head()

0     NaN
1     C85
2     NaN
3    C123
4     NaN
Name: Cabin, dtype: category
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [253]:
## creating Deck
df['Deck']= df['Cabin'].str[0].fillna('U').astype('category')
df['Deck'].value_counts()

Deck
U    687
C     59
B     47
D     33
E     32
A     15
F     13
G      4
T      1
Name: count, dtype: int64

### Use .loc to replace missing Embarked with most frequent embarkation port. Show code and explain why .loc is safer.

In [254]:
df['Embarked'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: category
Categories (3, object): ['C', 'Q', 'S']

In [255]:
df['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

### Show the memory usage before and after converting Name to category. Should you convert Name? Explain pros/cons.

In [256]:
df['Name'].memory_usage()

7260

In [257]:
df['Name'].astype('category')

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: category
Categories (891, object): ['Abbing, Mr. Anthony', 'Abbott, Mr. Rossmore Edward', 'Abbott, Mrs. Stanton (Rosa Hunt)', 'Abelson, Mr. Samuel', ..., 'de Pelsmaeker, Mr. Alfons', 'del Carlo, Mr. Sebastiano', 'van Billiard, Mr. Austin Blyler', 'van Melkebeke, Mr. Philemon']

In [258]:
df['Name'].memory_usage()

7260

### Create Fare_bin with 4 quantile bins using pd.qcut. Then show counts per bin and per Pclass.

In [259]:
df['Fare'].head()

0     7.2500
1    71.2833
2     7.9250
3    53.1000
4     8.0500
Name: Fare, dtype: float64

In [260]:
df['Fare_bin']= pd.qcut(df['Fare'], 4, labels=False)
pd.crosstab(df['Fare_bin'], df['Pclass'])

Pclass      1   2    3
Fare_bin
0           6   6  211
1           0  86  138
2          51  70  101
3         159  22   41

In [261]:
df['Pclass'].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

### Convert Survived to boolean bool and Survived_cat to category ('died','survived'). Explain choices for modeling vs presentation.

In [262]:
df['Survived'].head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [263]:
df['Survived_bool']= df['Survived'].astype('boolean')

In [264]:
df['Survived_bool'].value_counts()

Survived_bool
False    549
True     342
Name: count, dtype: Int64

In [265]:
df['Survived_label']= df['Survived'].map({0:'died', 1: 'servived'}).astype('category')
df['Survived_label'].value_counts()

Survived_label
died        549
servived    342
Name: count, dtype: int64

In [266]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked', 'FamilySize', 'IsAlone',
       'TicketPrefix', 'Deck', 'Fare_bin', 'Survived_bool', 'Survived_label'],
      dtype='object')

### Identify columns with mixed types (object columns containing numbers and strings). Show code to detect them.

In [267]:
for c in df.select_dtypes(['object']):
    #print(c, df[c].apply(lambda x : type(x)).value_counts().head())
    print(c, df[c].map(type).nunique()>1)

Name False
Sex False
Ticket False
TicketPrefix False

### Parse Name to get surname and first name. Create Surname, FirstName columns. Edge cases?

In [268]:
df['Name'].head(10)

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
5                                     Moran, Mr. James
6                              McCarthy, Mr. Timothy J
7                       Palsson, Master. Gosta Leonard
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9                  Nasser, Mrs. Nicholas (Adele Achem)
Name: Name, dtype: object

In [269]:
df['Surname']= df['Name'].str.split(',', n=1).str[0].str.strip()

In [270]:
df['FirstName']= df['Name'].str.split(',',n=1).str[1].str.strip()

In [271]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [272]:
df['FirstName'].head()

0                               Mr. Owen Harris
1    Mrs. John Bradley (Florence Briggs Thayer)
2                                   Miss. Laina
3            Mrs. Jacques Heath (Lily May Peel)
4                             Mr. William Henry
Name: FirstName, dtype: object

In [273]:
df['Surname'].head()

0       Braund
1      Cumings
2    Heikkinen
3     Futrelle
4        Allen
Name: Surname, dtype: object

###  Convert categorical columns (Sex, Embarked, Title, Deck) to category codes and save a mapping dict for each. Why map and store mapping?

In [274]:
# creaing final mapping for category code
final_mapping={}

In [275]:
# creatng category code
df['Sex']=df['Sex'].astype('category')
#df['Sex'].dtype
df['Sex_code']= df['Sex'].cat.codes

In [276]:
df['Sex'].sample(5)

139      male
251    female
555      male
607      male
203      male
Name: Sex, dtype: category
Categories (2, object): ['female', 'male']

In [277]:
df['Sex_code'].sample(10)

382    1
667    1
672    1
730    0
675    1
577    0
656    1
353    1
403    1
6      1
Name: Sex_code, dtype: int8

In [278]:
final_mapping['Sex']= dict(enumerate(df['Sex'].cat.categories))

In [279]:
final_mapping

{'Sex': {0: 'female', 1: 'male'}}

In [280]:
df['Embarked'].head()

0    S
1    C
2    S
3    S
4    S
Name: Embarked, dtype: category
Categories (3, object): ['C', 'Q', 'S']

In [281]:
df['Embarked_code']= df['Embarked'].cat.codes
final_mapping['Embarked']= dict(enumerate(df['Embarked'].cat.categories))
df['Embarked_code'].head()

0    2
1    0
2    2
3    2
4    2
Name: Embarked_code, dtype: int8

In [282]:
final_mapping

{'Sex': {0: 'female', 1: 'male'}, 'Embarked': {0: 'C', 1: 'Q', 2: 'S'}}

In [283]:
df['Deck_code']= df['Deck'].cat.codes
final_mapping['Deck']= dict(enumerate(df['Deck'].cat.categories))
df['Deck_code'].head()

0    8
1    2
2    8
3    2
4    8
Name: Deck_code, dtype: int8

In [284]:
final_mapping

{'Sex': {0: 'female', 1: 'male'},
 'Embarked': {0: 'C', 1: 'Q', 2: 'S'},
 'Deck': {0: 'A',
  1: 'B',
  2: 'C',
  3: 'D',
  4: 'E',
  5: 'F',
  6: 'G',
  7: 'T',
  8: 'U'}}

## EXPERT level Data Exploration

### Detect rows where Cabin contains multiple cabins (e.g., "C23 C25") and convert to a list column CabinList. Why might this matter?
It matters for group cabin and family grouping.

In [285]:
df['Cabin'].head()

0     NaN
1     C85
2     NaN
3    C123
4     NaN
Name: Cabin, dtype: category
Categories (147, object): ['A10', 'A14', 'A16', 'A19', ..., 'F38', 'F4', 'G6', 'T']

In [286]:
df['Cabin'].value_counts()

Cabin
G6             4
C23 C25 C27    4
B96 B98        4
F2             3
D              3
              ..
E63            1
E50            1
F G63          1
F38            1
T              1
Name: count, Length: 147, dtype: int64

In [287]:
df['Cabin_list']=df['Cabin'].str.split().apply(lambda x: x if isinstance(x, list) else [])
df['Cabin_list'].value_counts()

Cabin_list
[]                 687
[G6]                 4
[C23, C25, C27]      4
[B96, B98]           4
[F2]                 3
                  ...
[E17]                1
[A24]                1
[C50]                1
[B42]                1
[C148]               1
Name: count, Length: 148, dtype: int64

In [288]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 25 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PassengerId     891 non-null    int64
 1   Survived        891 non-null    int64
 2   Pclass          891 non-null    int64
 3   Name            891 non-null    object
 4   Sex             891 non-null    category
 5   Age             891 non-null    int64
 6   SibSp           891 non-null    Int8
 7   Parch           891 non-null    Int8
 8   Ticket          891 non-null    object
 9   Fare            891 non-null    float64
 10  Cabin           204 non-null    category
 11  Embarked        889 non-null    category
 12  FamilySize      891 non-null    Int8
 13  IsAlone         891 non-null    boolean
 14  TicketPrefix    891 non-null    object
 15  Deck            891 non-null    category
 16  Fare_bin        891 non-null    int64
 17  Survived_bool   891 non-null    boolean
 18  Survived_label  891 non-null    category
 19  Surname         891 non-null    object
 20  FirstName       891 non-null    object
 21  Sex_code        891 non-null    int8
 22  Embarked_code   891 non-null    int8
 23  Deck_code       891 non-null    int8
 24  Cabin_list      891 non-null    object
dtypes: Int8(3), boolean(2), category(5), float64(1), int64(5), int8(3), object(6)
memory usage: 106.1+ KB

In [289]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Deck,Fare_bin,Survived_bool,Survived_label,Surname,FirstName,Sex_code,Embarked_code,Deck_code,Cabin_list
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,...,U,0,False,died,Braund,Mr. Owen Harris,1,2,8,[]
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,...,C,3,True,servived,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,0,2,[C85]
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,...,U,1,True,servived,Heikkinen,Miss. Laina,0,2,8,[]
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,...,C,3,True,servived,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2,2,[C123]
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,...,U,1,False,died,Allen,Mr. William Henry,1,2,8,[]

### Show how to use pd.api.types.infer_dtype to detect columns with mixed numeric/string data. Use it on Ticket.

In [290]:
col_type= pd.api.types.infer_dtype(df['Ticket'],skipna=True)
col_type

'string'

In [291]:
df['Ticket'].sample(10)

750              29103
155           PC 17597
495               2627
518             226875
476              31027
87     SOTON/OQ 392086
813             347082
872                695
200             345770
716           PC 17757
Name: Ticket, dtype: object

In [292]:
col= pd.api.types.infer_dtype(df['PassengerId'], skipna=True)
col

'integer'

In [293]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,...,Deck,Fare_bin,Survived_bool,Survived_label,Surname,FirstName,Sex_code,Embarked_code,Deck_code,Cabin_list
0,1,0,3,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.2500,...,U,0,False,died,Braund,Mr. Owen Harris,1,2,8,[]
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38,1,0,PC 17599,71.2833,...,C,3,True,servived,Cumings,Mrs. John Bradley (Florence Briggs Thayer),0,0,2,[C85]
2,3,1,3,"Heikkinen, Miss. Laina",female,26,0,0,STON/O2. 3101282,7.9250,...,U,1,True,servived,Heikkinen,Miss. Laina,0,2,8,[]
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35,1,0,113803,53.1000,...,C,3,True,servived,Futrelle,Mrs. Jacques Heath (Lily May Peel),0,2,2,[C123]
4,5,0,3,"Allen, Mr. William Henry",male,35,0,0,373450,8.0500,...,U,1,False,died,Allen,Mr. William Henry,1,2,8,[]

### Implement a function that safely converts numeric-like object column to best numeric dtype (int if no NAs, else nullable Int). Provide code and apply to SibSp sample.

In [294]:
df['SibSp'].dtype

Int8Dtype()

### Show how to detect and fix leading/trailing whitespace and invisible unicode characters in string columns (Name, Ticket). Provide code.

In [295]:
df['Name'].head()

0                              Braund, Mr. Owen Harris
1    Cumings, Mrs. John Bradley (Florence Briggs Th...
2                               Heikkinen, Miss. Laina
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                             Allen, Mr. William Henry
Name: Name, dtype: object

In [296]:
df['Name']= df['Name'].str.strip().str.replace(r'\s+', ' ', regex=True)
df['Name']

0                                Braund, Mr. Owen Harris
1      Cumings, Mrs. John Bradley (Florence Briggs Th...
2                                 Heikkinen, Miss. Laina
3           Futrelle, Mrs. Jacques Heath (Lily May Peel)
4                               Allen, Mr. William Henry
                             ...
886                                Montvila, Rev. Juozas
887                         Graham, Miss. Margaret Edith
888             Johnston, Miss. Catherine Helen "Carrie"
889                                Behr, Mr. Karl Howell
890                                  Dooley, Mr. Patrick
Name: Name, Length: 891, dtype: object

In [297]:
df['Ticket']= df['Ticket'].apply(lambda x : x.strip())

In [298]:
df['Ticket'].sample(10)

536           113050
537         PC 17761
780             2687
84        SO/C 14885
362             2691
607           113804
135    SC/PARIS 2133
802           113760
651           231919
435           113760
Name: Ticket, dtype: object

### Does our dataset contain duplicate Customers if unique key = (Name + Ticket)?

In [332]:
df.loc[(df['Name']+df['Ticket']).duplicated()]

Empty DataFrame
Columns: [PassengerId, Survived, Pclass, Name, Sex, Age, SibSp, Parch, Ticket, Fare, Cabin, Embarked, FamilySize, IsAlone, TicketPrefix, Deck, Fare_bin, Survived_bool, Survived_label, Surname, FirstName, Sex_code, Embarked_code, Deck_code, Cabin_list, Title]
Index: []

[0 rows x 26 columns]

### Select the first cabin letter (deck) only for rows where Cabin is not null, using .loc and .str.

In [ ]:
df.loc[df['Cabin'].notna(),'Cabin'].str[0].value_counts()

Cabin
C    59
B    47
D    33
E    32
A    15
F    13
G     4
T     1
Name: count, dtype: int64

In [ ]:
df['Cabin'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 891 entries, 0 to 890
Series name: Cabin
Non-Null Count  Dtype
--------------  -----
204 non-null    category
dtypes: category(1)
memory usage: 7.1 KB